'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {startTestBridge,waitFor,completeJsonLines}=require('./helpers/temporary-bridge');
async function fixture(t){let events;const unset=Object.fromEntries(Object.keys(process.env).filter(k=>/^(RELAYBRIDGE_|PS_BRIDGE_)/.test(k)).map(k=>[k,undefined]));
 const bridge=await startTestBridge(t,root=>{events=path.join(root,'events.jsonl');const script=path.join(root,'provider.cjs');fs.writeFileSync(script,`const fs=require('node:fs');let prompt='';process.stdin.on('data',c=>prompt+=c);process.stdin.on('end',()=>{fs.appendFileSync(${JSON.stringify(events)},JSON.stringify({kind:process.argv[2],args:process.argv.slice(3),prompt})+'\\n');if(prompt.includes('INVALID_DECISION_FIXTURE'))console.log('not a decision');else if(prompt.includes('You are a senior project advisor'))console.log('ADVISOR_EVIDENCE: inspect the existing record contract first.');else if(prompt.includes('Perform this bounded read-only task'))console.log('Read-only inspection complete; no files changed.');else if(prompt.includes('Advisor result (must inform this decision)'))console.log(JSON.stringify({action:'allocate',text:'The advisor recommends inspecting the existing records first.',tasks:[{title:'Inspect records',kind:'read_only',provider:'codex',tier:'light',prompt:'Inspect the record contract read-only.'}]}));else console.log(JSON.stringify({action:'consult',question:'How should we preserve the existing record contract?'}));});`);
 return{_models:{discoverOnBoot:false},...Object.fromEntries(['codex','claude'].map(kind=>[kind,{label:kind,model:'fixture-standard',safe:[process.execPath],probe:[process.execPath,'--version'],version_probe:[process.execPath,'--version'],
 oneshot_safe:[process.execPath,script,kind,'--model','fixture-standard','--effort','medium'],oneshot_output_parser:'text',oneshot_safe_filesystem_policy:'read_only_enforced',oneshot_capabilities:{safe:['model_invocation','workspace_read','tool_use']},
 effort_flags:Object.fromEntries(['low','medium','high'].map(x=>[x,['--effort',x]])),model_tiers:Object.fromEntries(['light','standard','heavy'].map(x=>[x,{model:'fixture-'+x,args:['--model','fixture-'+x]}]))}]))};
 },{env:{...unset,RELAYBRIDGE_WARM_DIAG:'0',RELAYBRIDGE_REMOTE_MCP:'0'}});return{...bridge,events};}
test('project chat performs durable Codex → stronger advisor → Codex → worker round trip',{timeout:45000},async t=>{const b=await fixture(t);const created=await b.request('/api/project-workspace/projects',{actionId:'project_0001',name:'Project test',cwd:b.root});assert.equal(created.status,202,JSON.stringify(created.body));const {threadId,projectId}=created.body;
 const input={actionId:'message_0001',threadId,text:'Design the next project step.'};assert.equal((await b.request('/api/project-workspace/messages',input)).status,202);assert.equal((await b.request('/api/project-workspace/messages',input)).status,200);
 const state=await waitFor(async()=>{const v=(await b.request('/api/project-workspace/state')).body;return v.tasks?.[0]?.state==='completed'&&v;},35000);
 assert.equal(state.project.id,projectId);const events=completeJsonLines(b.events);assert.deepEqual(events.map(e=>e.kind),['codex','claude','codex','codex']);assert.ok(events[1].args.includes('fixture-heavy'));assert.ok(events[1].args.includes('high'));assert.match(events[2].prompt,/ADVISOR_EVIDENCE/);assert.match(events[2].prompt,/queued:t_pw_/);assert.equal(state.thread.messages.filter(m=>m.role==='user').length,1);assert.equal(state.tasks.length,1);const delivered=(await b.request('/api/tasks/'+state.tasks[0].queueTaskId+'/result')).body;assert.equal(delivered.resultPersisted,true);assert.equal(delivered.metadata.complete,true);
 const other=(await b.request('/api/project-workspace/projects',{actionId:'project_0002',name:'Second',cwd:b.root})).body;const empty=(await b.request('/api/project-workspace/state?projectId='+other.projectId)).body;assert.equal(empty.thread.messages.length,0);
 assert.equal((await b.request('/api/project-workspace/projects',{actionId:'project_0003',name:'Outside',cwd:path.resolve(b.root,'..')})).status,400);
 const rejected=await b.request('/api/project-workspace/messages',{actionId:'message_0001',threadId,text:'Different request'});assert.equal(rejected.status,409);
 const raw=await fetch(b.base+'/api/project-workspace/state');assert.equal(raw.status,401);
});
test('workspace routes retain CSP and coding tasks use valid real workflow IDs',{timeout:25000},async t=>{const b=await fixture(t);for(const route of ['/','/control-center.html']){const response=await fetch(b.base+route);assert.equal(response.status,200);assert.match(response.headers.get('content-security-policy'),/script-src-attr 'none'/);assert.equal(response.headers.get('x-frame-options'),'DENY');assert.match(await response.text(),/What are we building/);}
 const legacy=await fetch(b.base+'/terminal');assert.match(await legacy.text(),/<script nonce="[A-Za-z0-9+/=]+">\s*const API/);
 for(const route of ['//control-center.html','/%2fcontrol-center.html','//index.html']){const r=await fetch(b.base+route);assert.equal(r.status,404,route);}
 const created=(await b.request('/api/project-workspace/projects',{actionId:'project_0001',name:'Coding',cwd:b.root})).body;
 await b.request('/api/project-workspace/tasks',{actionId:'coding_00001',threadId:created.threadId,title:'Build change',prompt:'Implement a bounded change after planning.',kind:'coding'});
 const task=await waitFor(async()=>{const v=(await b.request('/api/project-workspace/state')).body.tasks[0];return v?.workflowId&&v;});
 const workflow=(await b.request('/api/workflows/'+task.workflowId)).body;assert.equal(workflow.workflow.runId,task.workflowId);assert.equal(workflow.workflow.permissionMode,'safe');assert.equal(workflow.workflow.writerLease,null);
});
